version: '3.9'

services:
  nginx-proxy:
    build: ./nginx-proxy/
    container_name: nginx-proxy
    restart: always
    networks:
      - reverseProxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    build:
      context: ./client
    networks:
      - intraNet
      - reverseProxy
    expose:
      - "3000"
    volumes:
      - ./client:/app
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=learn-abba.com

  api:
    build:
      context: ./server
    networks:
      - intraNet
    expose:
      - "3005:3005"
    working_dir: /usr/src/app
    env_file:
      - server/.build/.env
    command: >
      node server.js

networks:
  intraNet:
  reverseProxy:
