version: '3.9'

services:
  web:
    build:
      context: ./client
    networks:
      - intraNet
    ports:
      - "80:3000"
    volumes:
      - ./client:/app
    depends_on:
      - api

  api:
    build:
      context: ./server
    networks:
      - intraNet
    ports:
      - "3005:3005"
    working_dir: /usr/src/app
    command: >
      node server.js
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    networks:
      - intraNet
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  intraNet:
