version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    networks:
      - reverseProxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    build:
      context: ./client
    networks:
      - intraNet
      - reverseProxy
    expose:
      - "80:3000"
    volumes:
      - ./client:/app
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=nextjs.test

  api:
    build:
      context: ./server
    networks:
      - intraNet
    expose:
      - "3005:3005"
    working_dir: /usr/src/app
    command: >
      node server.js

networks:
  intraNet:
  reverseProxy: